/* Generated By:JavaCC: Do not edit this line. AdderConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AdderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAS = 5;
  /** RegularExpression Id. */
  int MENOS = 6;
  /** RegularExpression Id. */
  int MUL = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int LETRAX = 9;
  /** RegularExpression Id. */
  int LETRAY = 10;
  /** RegularExpression Id. */
  int LETRAZ = 11;
  /** RegularExpression Id. */
  int IGUAL = 12;
  /** RegularExpression Id. */
  int PUNTOCOMA = 13;
  /** RegularExpression Id. */
  int COMA = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int IDENTIFIER = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int CADENA = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"X\"",
    "\"Y\"",
    "\"Z\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<CADENA>",
  };

}
